# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

name: Build & Depoly Quarto Book

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
     run:
        working-directory: Book # The working directory path
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
        
      - uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: 0.9.105

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-renv@v2
          
      - name: Intsall Deps
        run: install.packages(c("rmarkdown", "knitr", "quarto"))
        shell: Rscript {0}
      - name: List contents before build
        run: ls -alhR && pwd
        shell: bash

      - name: Render book to all format
        # Add any command line argument needed
        run: |
          quarto render
      - name: List contents after build
        run: ls -alhR && pwd
        shell: bash
          
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: _book
