on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - uses: r-lib/actions/setup-r@v2
        with:
         r-version: '4.3.1' # The R version to download (if necessary) and use.

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2
            any::microbenchmark
            any::ggplot2
            any::remotes
            
      - name: Install remotes
        run: |
          Rscript -e 'remotes::install_github("AHomoudi/AquaFortR", subdir = "RPackage")'
           
      - name: Compile
        run: |
          cd QuartoBook/AquaFortR_Codes/
          R CMD SHLIB xcorr2D.f90
          R CMD SHLIB conv2D.f90
          R CMD SHLIB cape.f90
          #cd ../../

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: QuartoBook
          
      - name: Debug
        run: |
          ls -R 
          find . -type f -name "*QuartoBook.pdf*" -exec dirname "{}" \; |sort -u
          pwd
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: book-depoly # The branch the action should deploy to.
          folder: QuartoBook/_book # The folder the action should deploy.
          
