on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - uses: r-lib/actions/setup-r@v2
        with:
         r-version: '4.3.1' # The R version to download (if necessary) and use.

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: QuartoBook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  organize:                           
    needs: build-deploy                       # https://stackoverflow.com/a/65698892/13818750
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/gh-pages' #https://stackoverflow.com/a/58142412/13818750
    steps:
      - name: Check out repository
        uses: actions/checkout@v3