project:
  type: book

book:
  title: "QuartoBook"
  author: "Ahmed Homoudi"
  date: "16/08/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - scripts.qmd
    - package.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
    toc-depth: 2



